name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Cambia a versión que necesites

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Non hai requirements.txt"

      - name: Verificar execución de tests
        run: echo "🏆 TESTS EXECUTÁNDOSE AGORA!"

      - name: Executar tests
        run: python -m unittest test_utils.py

      - name: Verificar finalización de tests
        run: echo "✅ TESTS FINALIZADOS!"
